// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 24.1 (Build Build 1077 03/04/2025)
// Created on Mon Apr 27 14:20:55 2026

AU8 AU8_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.X(X_sig) ,	// input [7:0] X_sig
	.InA(InA_sig) ,	// input  InA_sig
	.InB(InB_sig) ,	// input  InB_sig
	.Out(Out_sig) ,	// input  Out_sig
	.Clear(Clear_sig) ,	// input  Clear_sig
	.Add_Subtract(Add_Subtract_sig) ,	// input  Add_Subtract_sig
	.Rout(Rout_sig) ,	// output [7:0] Rout_sig
	.OVR(OVR_sig) ,	// output  OVR_sig
	.ZERO(ZERO_sig) 	// output  ZERO_sig
);

