// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 24.1 (Build Build 1077 03/04/2025)
// Created on Mon Apr 27 14:28:45 2026

CU CU_inst
(
	.trig(trig_sig) ,	// input  trig_sig
	.reset(reset_sig) ,	// input  reset_sig
	.clk(clk_sig) ,	// input  clk_sig
	.val(val_sig) ,	// input [3:0] val_sig
	.Reset(Reset_sig) ,	// output  Reset_sig
	.LoadX(LoadX_sig) ,	// output  LoadX_sig
	.LoadY(LoadY_sig) ,	// output  LoadY_sig
	.AddSub(AddSub_sig) ,	// output  AddSub_sig
	.LoadR(LoadR_sig) ,	// output  LoadR_sig
	.IUAU(IUAU_sig) ,	// output  IUAU_sig
	.clearEntry(clearEntry_sig) ,	// output  clearEntry_sig
	.INVALID(INVALID_sig) 	// output  INVALID_sig
);

